logging:
  level:
    com.chippy: debug
  redis:
    redisson:
      config: classpath:redisson-dev.yml
server:
  port: 8081

enhance-object:
  scanner-package:
    - com.chippy.redis.example
  enhance-object-capacity: 16
  client: redisson